In [2]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [3]:
squared = []
for i in list_a:
  squared.append(i*i)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [5]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [6]:
import numpy as np


In [7]:
arr1 = np.array(list_a)

In [8]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [10]:
arr1/3

array([ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667,
        2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ,
        5.33333333,  5.66666667,  6.        ,  6.33333333,  6.66666667,
        7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
        8.66666667,  9.        ,  9.33333333,  9.66666667, 10.        ,
       10.33333333, 10.66666667, 11.        , 11.33333333, 11.66666667,
       12.        , 12.33333333, 12.66666667, 13.        , 13.33333333,
       13.66666667, 14.        , 14.33333333, 14.66666667, 15.        ,
       15.33333333, 15.66666667, 16.        , 16.33333333, 16.66666667,
       17.        , 17.33333333, 17.66666667, 18.        , 18.33333333,
       18.66666667, 19.        , 19.33333333, 19.66666667, 20.        ,
       20.33333333, 20.66666667, 21.        , 21.33333333, 21.66666667,
       22.        , 22.33333333, 22.66666667, 23.        , 23.33

In [11]:
arr2 = np.array([2,4,6,8])
arr2*2

array([ 4,  8, 12, 16])

In [12]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
arr3 = np.random.rand(1,10)
arr4 = np.random.rand(1,10)
print(arr3, arr4)

[[0.40810898 0.13696618 0.21093814 0.53184263 0.62972148 0.43667005
  0.13319763 0.46409017 0.46072727 0.41631181]] [[0.58585986 0.05307247 0.29191957 0.85234077 0.96577876 0.81142866
  0.58233288 0.31296086 0.31816624 0.84281364]]


In [18]:
arr3.dtype

dtype('float64')

In [19]:
arr3.shape

(1, 10)

In [20]:
arr3.ndim

2

In [21]:
arr1.ndim

1

In [22]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr1.shape

(9,)

In [24]:
arr3.size

10

In [27]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
arr2d.size, arr2d.shape, arr2d.ndim

(9, (3, 3), 2)

In [29]:
arr2d1 = np.random.rand(5,4)
arr2d1

array([[0.97341765, 0.1643904 , 0.22039359, 0.9575534 ],
       [0.65359027, 0.87138351, 0.41261108, 0.28103592],
       [0.81546449, 0.03096145, 0.28209591, 0.18287296],
       [0.60301566, 0.20894105, 0.20881409, 0.64505978],
       [0.5712913 , 0.2854995 , 0.9020565 , 0.95546471]])

In [31]:
arr3d = np.random.rand(3,4,5)
arr3d

array([[[0.4231055 , 0.95530634, 0.77625056, 0.61486441, 0.87932579],
        [0.84615285, 0.4913874 , 0.26965701, 0.01172118, 0.74953515],
        [0.67154195, 0.57664881, 0.7033398 , 0.12014982, 0.07680162],
        [0.49362637, 0.63579754, 0.08857693, 0.0721771 , 0.71803829]],

       [[0.88253781, 0.28732476, 0.08443777, 0.06942728, 0.01237709],
        [0.85566094, 0.55768143, 0.74264122, 0.89970173, 0.94442333],
        [0.25277137, 0.79062024, 0.7696524 , 0.11468338, 0.00184426],
        [0.26788799, 0.16969429, 0.88398814, 0.71676717, 0.30556021]],

       [[0.75631986, 0.66237414, 0.83498696, 0.46745716, 0.76859729],
        [0.01877843, 0.25159458, 0.5031891 , 0.60987797, 0.66401622],
        [0.87113628, 0.86975143, 0.47913839, 0.86436519, 0.25789768],
        [0.59638309, 0.78749897, 0.73538038, 0.87759505, 0.29185071]]])

In [37]:
arr3d1 = np.arange(64).reshape(4,4,4)
arr3d1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])