In [1]:
list_a = list(range(1,100))
print(list_a)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [2]:
squared = []
for i in list_a:
  squared.append(i*i)
print(squared)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [3]:
print([a**2 for a in list_a])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]


In [4]:
import numpy as np


In [5]:
arr1 = np.array(list_a)

In [6]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
arr1**2

array([   1,    4,    9,   16,   25,   36,   49,   64,   81,  100,  121,
        144,  169,  196,  225,  256,  289,  324,  361,  400,  441,  484,
        529,  576,  625,  676,  729,  784,  841,  900,  961, 1024, 1089,
       1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936,
       2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025,
       3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356,
       4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929,
       6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744,
       7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801])

In [8]:
arr1/3

array([ 0.33333333,  0.66666667,  1.        ,  1.33333333,  1.66666667,
        2.        ,  2.33333333,  2.66666667,  3.        ,  3.33333333,
        3.66666667,  4.        ,  4.33333333,  4.66666667,  5.        ,
        5.33333333,  5.66666667,  6.        ,  6.33333333,  6.66666667,
        7.        ,  7.33333333,  7.66666667,  8.        ,  8.33333333,
        8.66666667,  9.        ,  9.33333333,  9.66666667, 10.        ,
       10.33333333, 10.66666667, 11.        , 11.33333333, 11.66666667,
       12.        , 12.33333333, 12.66666667, 13.        , 13.33333333,
       13.66666667, 14.        , 14.33333333, 14.66666667, 15.        ,
       15.33333333, 15.66666667, 16.        , 16.33333333, 16.66666667,
       17.        , 17.33333333, 17.66666667, 18.        , 18.33333333,
       18.66666667, 19.        , 19.33333333, 19.66666667, 20.        ,
       20.33333333, 20.66666667, 21.        , 21.33333333, 21.66666667,
       22.        , 22.33333333, 22.66666667, 23.        , 23.33

In [9]:
arr2 = np.array([2,4,6,8])
arr2*2

array([ 4,  8, 12, 16])

In [10]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
arr2 = np.arange(10)
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr3 = np.random.rand(1,10)
arr4 = np.random.rand(1,10)
print(arr3, arr4)

[[0.27470093 0.42345848 0.48481707 0.80294287 0.62644931 0.53099686
  0.50575717 0.43418846 0.85701839 0.52792036]] [[0.65492613 0.20747107 0.90671215 0.52380458 0.29568534 0.90942267
  0.36497007 0.00394957 0.92088275 0.88273627]]


In [13]:
arr3.dtype

dtype('float64')

In [14]:
arr3.shape

(1, 10)

In [15]:
arr3.ndim

2

In [16]:
arr1.ndim

1

In [17]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr1.shape

(9,)

In [19]:
arr3.size

10

In [20]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
arr2d.size, arr2d.shape, arr2d.ndim

(9, (3, 3), 2)

In [22]:
arr2d1 = np.random.rand(5,4)
arr2d1

array([[0.45914898, 0.83919709, 0.42677479, 0.6436944 ],
       [0.20380822, 0.34727452, 0.34346001, 0.61145862],
       [0.40500958, 0.50844579, 0.27953507, 0.60430292],
       [0.1023699 , 0.04664706, 0.66851361, 0.66471721],
       [0.67433254, 0.90914384, 0.3644227 , 0.66895423]])

In [23]:
arr3d = np.random.rand(3,4,5)
arr3d

array([[[0.29878324, 0.95065141, 0.8073297 , 0.57215581, 0.33207445],
        [0.87695402, 0.71579122, 0.13749924, 0.67257449, 0.6512482 ],
        [0.97391591, 0.46687888, 0.48119861, 0.01011127, 0.17202906],
        [0.62457095, 0.17147332, 0.9707923 , 0.61610653, 0.46643158]],

       [[0.99534658, 0.13477287, 0.81538828, 0.98709075, 0.81717215],
        [0.62768016, 0.99449084, 0.62397752, 0.0338753 , 0.03675645],
        [0.58785241, 0.44110575, 0.37462271, 0.69921423, 0.29925108],
        [0.94369443, 0.20101358, 0.01363114, 0.66130148, 0.25643427]],

       [[0.36327314, 0.86582776, 0.77022757, 0.776449  , 0.53278996],
        [0.7465666 , 0.93768926, 0.72342723, 0.6348117 , 0.31916254],
        [0.30429014, 0.13103764, 0.86200586, 0.78734259, 0.43736205],
        [0.26220839, 0.09203501, 0.0413853 , 0.96750617, 0.79249846]]])

In [24]:
arr3d1 = np.arange(64).reshape(4,4,4)
arr3d1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])